package com.aerosimo.apps;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;

/**
 * @author Aerosimo
 *
 */
class SendMailTest {

    @BeforeAll
    static void initAll() {
    }

    @BeforeEach
    void init() {
    }	
    @AfterEach
    void tearDown() {
    }

    @AfterAll
    static void tearDownAll() {
    }

	/**
	 * Test method for {@link com.aerosimo.acr.SendMail#SendEmail(java.lang.String, java.lang.String, java.lang.String, java.lang.String)}.
	 */
	@Test
	@DisplayName("Unit Testing SendMail")
	void testSendEmail() {
		// create the connection object.
		SendMail mailer;
		mailer = new SendMail();
		// Now set the actual message
		String emailMessage;
		emailMessage = "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "   <head>\r\n"
				+ "      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=US-ASCII\">\r\n"
				+ "      <meta name=\"viewport\" content=\"width=device-width\">\r\n"
				+ "   </head>\r\n"
				+ "   <body style=\"-moz-box-sizing: border-box; -ms-text-size-adjust: 100%; -webkit-box-sizing: border-box; -webkit-text-size-adjust: 100%; box-sizing: border-box; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 22px; margin: 0; min-width: 100%; padding: 0; text-align: left; width: 100% !important\">\r\n"
				+ "      <style type=\"text/css\">\r\n"
				+ "         body {\r\n"
				+ "         width: 100% !important; min-width: 100%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; margin: 0; padding: 0; -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box;\r\n"
				+ "         }\r\n"
				+ "         .ExternalClass {\r\n"
				+ "         width: 100%;\r\n"
				+ "         }\r\n"
				+ "         .ExternalClass {\r\n"
				+ "         line-height: 100%;\r\n"
				+ "         }\r\n"
				+ "         #backgroundTable {\r\n"
				+ "         margin: 0; padding: 0; width: 100% !important; line-height: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         img {\r\n"
				+ "         outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; width: auto; max-width: 100%; clear: both; display: block;\r\n"
				+ "         }\r\n"
				+ "         body {\r\n"
				+ "         color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-weight: normal; padding: 0; margin: 0; text-align: left; line-height: 1.3;\r\n"
				+ "         }\r\n"
				+ "         body {\r\n"
				+ "         font-size: 16px; line-height: 1.3;\r\n"
				+ "         }\r\n"
				+ "         a:hover {\r\n"
				+ "         color: #1f54ed;\r\n"
				+ "         }\r\n"
				+ "         a:active {\r\n"
				+ "         color: #1f54ed;\r\n"
				+ "         }\r\n"
				+ "         a:visited {\r\n"
				+ "         color: #4E78F1;\r\n"
				+ "         }\r\n"
				+ "         h1 a:visited {\r\n"
				+ "         color: #4E78F1;\r\n"
				+ "         }\r\n"
				+ "         h2 a:visited {\r\n"
				+ "         color: #4E78F1;\r\n"
				+ "         }\r\n"
				+ "         h3 a:visited {\r\n"
				+ "         color: #4E78F1;\r\n"
				+ "         }\r\n"
				+ "         h4 a:visited {\r\n"
				+ "         color: #4E78F1;\r\n"
				+ "         }\r\n"
				+ "         h5 a:visited {\r\n"
				+ "         color: #4E78F1;\r\n"
				+ "         }\r\n"
				+ "         h6 a:visited {\r\n"
				+ "         color: #4E78F1;\r\n"
				+ "         }\r\n"
				+ "         table.button:hover table tr td a {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button:active table tr td a {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button table tr td a:visited {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.tiny:hover table tr td a {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.tiny:active table tr td a {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.tiny table tr td a:visited {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.small:hover table tr td a {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.small:active table tr td a {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.small table tr td a:visited {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.large:hover table tr td a {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.large:active table tr td a {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.large table tr td a:visited {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button:hover table td {\r\n"
				+ "         background: #1f54ed; color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button:visited table td {\r\n"
				+ "         background: #1f54ed; color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button:active table td {\r\n"
				+ "         background: #1f54ed; color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button:hover table a {\r\n"
				+ "         border: 0 solid #1f54ed;\r\n"
				+ "         }\r\n"
				+ "         table.button:visited table a {\r\n"
				+ "         border: 0 solid #1f54ed;\r\n"
				+ "         }\r\n"
				+ "         table.button:active table a {\r\n"
				+ "         border: 0 solid #1f54ed;\r\n"
				+ "         }\r\n"
				+ "         table.button.secondary:hover table td {\r\n"
				+ "         background: #fefefe; color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.secondary:hover table a {\r\n"
				+ "         border: 0 solid #fefefe;\r\n"
				+ "         }\r\n"
				+ "         table.button.secondary:hover table td a {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.secondary:active table td a {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.secondary table td a:visited {\r\n"
				+ "         color: #FFFFFF;\r\n"
				+ "         }\r\n"
				+ "         table.button.success:hover table td {\r\n"
				+ "         background: #009482;\r\n"
				+ "         }\r\n"
				+ "         table.button.success:hover table a {\r\n"
				+ "         border: 0 solid #009482;\r\n"
				+ "         }\r\n"
				+ "         table.button.alert:hover table td {\r\n"
				+ "         background: #ff6131;\r\n"
				+ "         }\r\n"
				+ "         table.button.alert:hover table a {\r\n"
				+ "         border: 0 solid #ff6131;\r\n"
				+ "         }\r\n"
				+ "         table.button.warning:hover table td {\r\n"
				+ "         background: #fcae1a;\r\n"
				+ "         }\r\n"
				+ "         table.button.warning:hover table a {\r\n"
				+ "         border: 0px solid #fcae1a;\r\n"
				+ "         }\r\n"
				+ "         .thumbnail:hover {\r\n"
				+ "         box-shadow: 0 0 6px 1px rgba(78,120,241,0.5);\r\n"
				+ "         }\r\n"
				+ "         .thumbnail:focus {\r\n"
				+ "         box-shadow: 0 0 6px 1px rgba(78,120,241,0.5);\r\n"
				+ "         }\r\n"
				+ "         body.outlook p {\r\n"
				+ "         display: inline !important;\r\n"
				+ "         }\r\n"
				+ "         body {\r\n"
				+ "         font-weight: normal; font-size: 16px; line-height: 22px;\r\n"
				+ "         }\r\n"
				+ "         @media only screen and (max-width: 596px) {\r\n"
				+ "         .small-float-center {\r\n"
				+ "         margin: 0 auto !important; float: none !important; text-align: center !important;\r\n"
				+ "         }\r\n"
				+ "         .small-text-center {\r\n"
				+ "         text-align: center !important;\r\n"
				+ "         }\r\n"
				+ "         .small-text-left {\r\n"
				+ "         text-align: left !important;\r\n"
				+ "         }\r\n"
				+ "         .small-text-right {\r\n"
				+ "         text-align: right !important;\r\n"
				+ "         }\r\n"
				+ "         .hide-for-large {\r\n"
				+ "         display: block !important; width: auto !important; overflow: visible !important; max-height: none !important; font-size: inherit !important; line-height: inherit !important;\r\n"
				+ "         }\r\n"
				+ "         table.body table.container .hide-for-large {\r\n"
				+ "         display: table !important; width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body table.container .row.hide-for-large {\r\n"
				+ "         display: table !important; width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body table.container .callout-inner.hide-for-large {\r\n"
				+ "         display: table-cell !important; width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body table.container .show-for-large {\r\n"
				+ "         display: none !important; width: 0; mso-hide: all; overflow: hidden;\r\n"
				+ "         }\r\n"
				+ "         table.body img {\r\n"
				+ "         width: auto; height: auto;\r\n"
				+ "         }\r\n"
				+ "         table.body center {\r\n"
				+ "         min-width: 0 !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .container {\r\n"
				+ "         width: 95% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .columns {\r\n"
				+ "         height: auto !important; -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box; padding-left: 16px !important; padding-right: 16px !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .column {\r\n"
				+ "         height: auto !important; -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box; padding-left: 16px !important; padding-right: 16px !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .columns .column {\r\n"
				+ "         padding-left: 0 !important; padding-right: 0 !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .columns .columns {\r\n"
				+ "         padding-left: 0 !important; padding-right: 0 !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .column .column {\r\n"
				+ "         padding-left: 0 !important; padding-right: 0 !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .column .columns {\r\n"
				+ "         padding-left: 0 !important; padding-right: 0 !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .collapse .columns {\r\n"
				+ "         padding-left: 0 !important; padding-right: 0 !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .collapse .column {\r\n"
				+ "         padding-left: 0 !important; padding-right: 0 !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-1 {\r\n"
				+ "         display: inline-block !important; width: 8.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-1 {\r\n"
				+ "         display: inline-block !important; width: 8.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-2 {\r\n"
				+ "         display: inline-block !important; width: 16.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-2 {\r\n"
				+ "         display: inline-block !important; width: 16.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-3 {\r\n"
				+ "         display: inline-block !important; width: 25% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-3 {\r\n"
				+ "         display: inline-block !important; width: 25% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-4 {\r\n"
				+ "         display: inline-block !important; width: 33.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-4 {\r\n"
				+ "         display: inline-block !important; width: 33.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-5 {\r\n"
				+ "         display: inline-block !important; width: 41.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-5 {\r\n"
				+ "         display: inline-block !important; width: 41.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-6 {\r\n"
				+ "         display: inline-block !important; width: 50% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-6 {\r\n"
				+ "         display: inline-block !important; width: 50% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-7 {\r\n"
				+ "         display: inline-block !important; width: 58.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-7 {\r\n"
				+ "         display: inline-block !important; width: 58.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-8 {\r\n"
				+ "         display: inline-block !important; width: 66.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-8 {\r\n"
				+ "         display: inline-block !important; width: 66.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-9 {\r\n"
				+ "         display: inline-block !important; width: 75% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-9 {\r\n"
				+ "         display: inline-block !important; width: 75% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-10 {\r\n"
				+ "         display: inline-block !important; width: 83.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-10 {\r\n"
				+ "         display: inline-block !important; width: 83.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-11 {\r\n"
				+ "         display: inline-block !important; width: 91.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-11 {\r\n"
				+ "         display: inline-block !important; width: 91.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         td.small-12 {\r\n"
				+ "         display: inline-block !important; width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         th.small-12 {\r\n"
				+ "         display: inline-block !important; width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         .columns td.small-12 {\r\n"
				+ "         display: block !important; width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         .column td.small-12 {\r\n"
				+ "         display: block !important; width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         .columns th.small-12 {\r\n"
				+ "         display: block !important; width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         .column th.small-12 {\r\n"
				+ "         display: block !important; width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-1 {\r\n"
				+ "         margin-left: 8.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-1 {\r\n"
				+ "         margin-left: 8.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-2 {\r\n"
				+ "         margin-left: 16.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-2 {\r\n"
				+ "         margin-left: 16.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-3 {\r\n"
				+ "         margin-left: 25% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-3 {\r\n"
				+ "         margin-left: 25% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-4 {\r\n"
				+ "         margin-left: 33.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-4 {\r\n"
				+ "         margin-left: 33.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-5 {\r\n"
				+ "         margin-left: 41.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-5 {\r\n"
				+ "         margin-left: 41.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-6 {\r\n"
				+ "         margin-left: 50% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-6 {\r\n"
				+ "         margin-left: 50% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-7 {\r\n"
				+ "         margin-left: 58.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-7 {\r\n"
				+ "         margin-left: 58.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-8 {\r\n"
				+ "         margin-left: 66.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-8 {\r\n"
				+ "         margin-left: 66.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-9 {\r\n"
				+ "         margin-left: 75% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-9 {\r\n"
				+ "         margin-left: 75% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-10 {\r\n"
				+ "         margin-left: 83.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-10 {\r\n"
				+ "         margin-left: 83.333333% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body td.small-offset-11 {\r\n"
				+ "         margin-left: 91.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body th.small-offset-11 {\r\n"
				+ "         margin-left: 91.666666% !important;\r\n"
				+ "         }\r\n"
				+ "         table.body table.columns td.expander {\r\n"
				+ "         display: none !important;\r\n"
				+ "         }\r\n"
				+ "         table.body table.columns th.expander {\r\n"
				+ "         display: none !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .right-text-pad {\r\n"
				+ "         padding-left: 10px !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .text-pad-right {\r\n"
				+ "         padding-left: 10px !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .left-text-pad {\r\n"
				+ "         padding-right: 10px !important;\r\n"
				+ "         }\r\n"
				+ "         table.body .text-pad-left {\r\n"
				+ "         padding-right: 10px !important;\r\n"
				+ "         }\r\n"
				+ "         table.menu {\r\n"
				+ "         width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         table.menu td {\r\n"
				+ "         width: auto !important; display: inline-block !important;\r\n"
				+ "         }\r\n"
				+ "         table.menu th {\r\n"
				+ "         width: auto !important; display: inline-block !important;\r\n"
				+ "         }\r\n"
				+ "         table.menu.vertical td {\r\n"
				+ "         display: block !important;\r\n"
				+ "         }\r\n"
				+ "         table.menu.vertical th {\r\n"
				+ "         display: block !important;\r\n"
				+ "         }\r\n"
				+ "         table.menu.small-vertical td {\r\n"
				+ "         display: block !important;\r\n"
				+ "         }\r\n"
				+ "         table.menu.small-vertical th {\r\n"
				+ "         display: block !important;\r\n"
				+ "         }\r\n"
				+ "         table.menu[align=\"center\"] {\r\n"
				+ "         width: auto !important;\r\n"
				+ "         }\r\n"
				+ "         table.button.small-expand {\r\n"
				+ "         width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         table.button.small-expanded {\r\n"
				+ "         width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         table.button.small-expand table {\r\n"
				+ "         width: 100%;\r\n"
				+ "         }\r\n"
				+ "         table.button.small-expanded table {\r\n"
				+ "         width: 100%;\r\n"
				+ "         }\r\n"
				+ "         table.button.small-expand table a {\r\n"
				+ "         text-align: center !important; width: 100% !important; padding-left: 0 !important; padding-right: 0 !important;\r\n"
				+ "         }\r\n"
				+ "         table.button.small-expanded table a {\r\n"
				+ "         text-align: center !important; width: 100% !important; padding-left: 0 !important; padding-right: 0 !important;\r\n"
				+ "         }\r\n"
				+ "         table.button.small-expand center {\r\n"
				+ "         min-width: 0;\r\n"
				+ "         }\r\n"
				+ "         table.button.small-expanded center {\r\n"
				+ "         min-width: 0;\r\n"
				+ "         }\r\n"
				+ "         table.body .container {\r\n"
				+ "         width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         }\r\n"
				+ "         @media only screen and (min-width: 732px) {\r\n"
				+ "         table.body table.milkyway-email-card {\r\n"
				+ "         width: 525px !important;\r\n"
				+ "         }\r\n"
				+ "         table.body table.emailer-footer {\r\n"
				+ "         width: 525px !important;\r\n"
				+ "         }\r\n"
				+ "         }\r\n"
				+ "         @media only screen and (max-width: 731px) {\r\n"
				+ "         table.body table.milkyway-email-card {\r\n"
				+ "         width: 320px !important;\r\n"
				+ "         }\r\n"
				+ "         table.body table.emailer-footer {\r\n"
				+ "         width: 320px !important;\r\n"
				+ "         }\r\n"
				+ "         }\r\n"
				+ "         @media only screen and (max-width: 320px) {\r\n"
				+ "         table.body table.milkyway-email-card {\r\n"
				+ "         width: 100% !important; border-radius: 0; box-sizing: none;\r\n"
				+ "         }\r\n"
				+ "         table.body table.emailer-footer {\r\n"
				+ "         width: 100% !important; border-radius: 0; box-sizing: none;\r\n"
				+ "         }\r\n"
				+ "         }\r\n"
				+ "         @media only screen and (max-width: 280px) {\r\n"
				+ "         table.body table.milkyway-email-card .milkyway-content {\r\n"
				+ "         width: 100% !important;\r\n"
				+ "         }\r\n"
				+ "         }\r\n"
				+ "         @media (min-width: 596px) {\r\n"
				+ "         .milkyway-header {\r\n"
				+ "         width: 11%;\r\n"
				+ "         }\r\n"
				+ "         }\r\n"
				+ "         @media (max-width: 596px) {\r\n"
				+ "         .milkyway-header {\r\n"
				+ "         width: 50%;\r\n"
				+ "         }\r\n"
				+ "         .emailer-footer .emailer-border-bottom {\r\n"
				+ "         border-bottom: 0.5px solid #E2E5E7;\r\n"
				+ "         }\r\n"
				+ "         .emailer-footer .make-you-smile {\r\n"
				+ "         margin-top: 24px;\r\n"
				+ "         }\r\n"
				+ "         .emailer-footer .make-you-smile .email-tag-line {\r\n"
				+ "         width: 80%; position: relative; left: 10%;\r\n"
				+ "         }\r\n"
				+ "         .emailer-footer .make-you-smile .universe-address {\r\n"
				+ "         margin-bottom: 10px !important;\r\n"
				+ "         }\r\n"
				+ "         .emailer-footer .make-you-smile .email-tag-line {\r\n"
				+ "         margin-bottom: 10px !important;\r\n"
				+ "         }\r\n"
				+ "         .have-questions-text {\r\n"
				+ "         width: 70%;\r\n"
				+ "         }\r\n"
				+ "         .hide-on-small {\r\n"
				+ "         display: none;\r\n"
				+ "         }\r\n"
				+ "         .product-card-stacked-row .thumbnail-image {\r\n"
				+ "         max-width: 32% !important;\r\n"
				+ "         }\r\n"
				+ "         .product-card-stacked-row .thumbnail-content p {\r\n"
				+ "         width: 64%;\r\n"
				+ "         }\r\n"
				+ "         .welcome-subcontent {\r\n"
				+ "         text-align: left; margin: 20px 0 10px;\r\n"
				+ "         }\r\n"
				+ "         .milkyway-title {\r\n"
				+ "         padding: 16px;\r\n"
				+ "         }\r\n"
				+ "         .meta-data {\r\n"
				+ "         text-align: center;\r\n"
				+ "         }\r\n"
				+ "         .label {\r\n"
				+ "         text-align: center;\r\n"
				+ "         }\r\n"
				+ "         .welcome-email .wavey-background-subcontent {\r\n"
				+ "         width: calc(100% - 32px);\r\n"
				+ "         }\r\n"
				+ "         }\r\n"
				+ "         @media (min-width: 597px) {\r\n"
				+ "         .emailer-footer .show-on-mobile {\r\n"
				+ "         display: none;\r\n"
				+ "         }\r\n"
				+ "         .emailer-footer .emailer-border-bottom {\r\n"
				+ "         border-bottom: none;\r\n"
				+ "         }\r\n"
				+ "         .have-questions-text {\r\n"
				+ "         border-bottom: none;\r\n"
				+ "         }\r\n"
				+ "         .hide-on-large {\r\n"
				+ "         display: none;\r\n"
				+ "         }\r\n"
				+ "         .milkyway-title {\r\n"
				+ "         padding: 55px 55px 16px;\r\n"
				+ "         }\r\n"
				+ "         }\r\n"
				+ "         @media only screen and (max-width: 290px) {\r\n"
				+ "         table.container.your-tickets .tickets-container {\r\n"
				+ "         width: 100%;\r\n"
				+ "         }\r\n"
				+ "         }\r\n"
				+ "      </style>\r\n"
				+ "      <table class=\"body\" data-made-with-foundation=\"\" style=\"background: #FAFAFA; border-collapse: collapse; border-spacing: 0; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; height: 100%; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\" bgcolor=\"#FAFAFA\">\r\n"
				+ "         <tbody>\r\n"
				+ "            <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "               <td class=\"center\" align=\"center\" valign=\"top\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\">\r\n"
				+ "                  <center style=\"min-width: 580px; width: 100%\">\r\n"
				+ "                     <table class=\" spacer  float-center\" align=\"center\" style=\"border-collapse: collapse; border-spacing: 0; float: none; margin: 0 auto; padding: 0; text-align: center; vertical-align: top; width: 100%\">\r\n"
				+ "                        <tbody>\r\n"
				+ "                           <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                              <td height=\"20px\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 20px; font-weight: normal; hyphens: auto; line-height: 20px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">&nbsp;</td>\r\n"
				+ "                           </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                     </table>\r\n"
				+ "                     <table class=\"header-spacer spacer  float-center\" align=\"center\" style=\"border-collapse: collapse; border-spacing: 0; float: none; line-height: 60px; margin: 0 auto; padding: 0; text-align: center; vertical-align: top; width: 100%\">\r\n"
				+ "                        <tbody>\r\n"
				+ "                           <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                              <td height=\"16px\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 16px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">&nbsp;</td>\r\n"
				+ "                           </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                     </table>\r\n"
				+ "                     <table class=\"header-spacer-bottom spacer  float-center\" align=\"center\" style=\"border-collapse: collapse; border-spacing: 0; float: none; line-height: 30px; margin: 0 auto; padding: 0; text-align: center; vertical-align: top; width: 100%\">\r\n"
				+ "                        <tbody>\r\n"
				+ "                           <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                              <td height=\"16px\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 16px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">&nbsp;</td>\r\n"
				+ "                           </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                     </table>\r\n"
				+ "                     <table class=\"milkyway-email-card container float-center\" align=\"center\" style=\"background: #FFFFFF; border-collapse: collapse; border-radius: 6px; border-spacing: 0; box-shadow: 0 1px 8px 0 rgba(28,35,43,0.15); float: none; margin: 0 auto; overflow: hidden; padding: 0; text-align: center; vertical-align: top; width: 580px\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                        <tbody>\r\n"
				+ "                           <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                              <td style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">\r\n"
				+ "                                 <table class=\"milkyway-content welcome-email container\" align=\"center\" style=\"background: #FFFFFF; border-collapse: collapse; border-spacing: 0; hyphens: none; margin: auto; max-width: 100%; padding: 0; text-align: inherit; vertical-align: top; width: 280px !important\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                       <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                          <td style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">\r\n"
				+ "                                             <table class=\" spacer \" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <td height=\"50px\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 50px; font-weight: normal; hyphens: auto; line-height: 50px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">&nbsp;</td>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                             <table class=\" row\" style=\"border-collapse: collapse; border-spacing: 0; display: table; padding: 0; position: relative; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <th class=\" small-12 large-12 columns first last\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; text-align: left; width: 564px\" align=\"left\">\r\n"
				+ "                                                         <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                            <tbody>\r\n"
				+ "                                                               <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                                  <th style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left\" align=\"left\">\r\n"
				+ "                                                                     <center style=\"min-width: 0; width: 100%\">\r\n"
				+ "                                                                        <img width=\"250\" src=\"https://i.ibb.co/Rb9GB39/3401.jpg\" align=\"center\" class=\" float-center float-center float-center\" style=\"-ms-interpolation-mode: bicubic; clear: both; display: block; float: none; margin: 0 auto; max-width: 100%; outline: none; text-align: center; text-decoration: none; width: auto\">\r\n"
				+ "                                                                     </center>\r\n"
				+ "                                                                  </th>\r\n"
				+ "                                                                  <th class=\"expander\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; visibility: hidden; width: 0\" align=\"left\"></th>\r\n"
				+ "                                                               </tr>\r\n"
				+ "                                                            </tbody>\r\n"
				+ "                                                         </table>\r\n"
				+ "                                                      </th>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                             <table class=\"milkyway-content row\" style=\"border-collapse: collapse; border-spacing: 0; display: table; hyphens: none; margin: auto; max-width: 100%; padding: 0; position: relative; text-align: left; vertical-align: top; width: 280px !important\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <th class=\" small-12 large-12 columns first last\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; text-align: left; width: 564px\" align=\"left\">\r\n"
				+ "                                                         <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                            <tbody>\r\n"
				+ "                                                               <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                                  <th style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left\" align=\"left\">\r\n"
				+ "                                                                     <h1 class=\"welcome-header\" style=\"color: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 24px; font-weight: 600; hyphens: none; line-height: 30px; margin: 0 0 24px; padding: 0; text-align: left; width: 100%; word-wrap: normal\" align=\"left\">Unit Testing Notication</h1>\r\n"
				+ "                                                                     <h2 class=\"welcome-subcontent\" style=\"color: #6F7881; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 300; line-height: 22px; margin: 0; padding: 0; text-align: center; width: 100%; word-wrap: normal\" align=\"left\">Unit tests are typically automated tests written and run by software developers to ensure that a section of an application (known as the \"unit\") meets its design and behaves as intended. In procedural programming, a unit could be an entire module, but it is more commonly an individual function or procedure.</h2>\r\n"
				+ "                                                                  </th>\r\n"
				+ "                                                                  <th class=\"expander\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; visibility: hidden; width: 0\" align=\"left\"></th>\r\n"
				+ "                                                               </tr>\r\n"
				+ "                                                            </tbody>\r\n"
				+ "                                                         </table>\r\n"
				+ "                                                      </th>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                             <table class=\" spacer \" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <td height=\"30px\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 30px; font-weight: normal; hyphens: auto; line-height: 30px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">&nbsp;</td>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                             <table class=\"milkyway-content wrapper\" align=\"center\" style=\"border-collapse: collapse; border-spacing: 0; hyphens: none; margin: auto; max-width: 100%; padding: 0; text-align: left; vertical-align: top; width: 280px !important\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <td class=\"wrapper-inner\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\"></td>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                             <table class=\"milkyway-content row\" style=\"border-collapse: collapse; border-spacing: 0; display: table; hyphens: none; margin: auto; max-width: 100%; padding: 0; position: relative; text-align: left; vertical-align: top; width: 280px !important\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <th class=\"milkyway-padding small-12 large-12 columns first last\" valign=\"middle\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; text-align: left; width: 564px\" align=\"left\">\r\n"
				+ "                                                         <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                            <tbody>\r\n"
				+ "                                                               <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                                  <th style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left\" align=\"left\">\r\n"
				+ "                                                                     <table class=\"cta-text primary radius expanded button\" style=\"border-collapse: collapse; border-spacing: 0; font-size: 14px; font-weight: 400; line-height: 0; margin: 0 0 16px; padding: 0; text-align: left; vertical-align: top; width: 100% !important\">\r\n"
				+ "                                                                        <tbody>\r\n"
				+ "                                                                           <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                                              <td style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">\r\n"
				+ "                                                                                 <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                                                    <tbody>\r\n"
				+ "                                                                                       <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                                                          <td style=\"-moz-hyphens: auto; -webkit-hyphens: auto; background: #00aeff; border: 2px none #4e78f1; border-collapse: collapse !important; border-radius: 6px; color: #FFFFFF; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" bgcolor=\"#4E78F1\" valign=\"top\">\r\n"
				+ "                                                                                             <a href=\"https://www.universe.com/create?ref=uniiverse-milkyway%2Ftransactional_emailer-welcome_email_general\" style=\"border: 0 solid #4e78f1; border-radius: 6px; color: #FFFFFF; display: inline-block; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: bold; line-height: 1.3; margin: 0; padding: 13px 0; text-align: center; text-decoration: none; width: 100%\" target=\"_blank\">\r\n"
				+ "                                                                                                <p class=\"text-center\" style=\"color: white; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 300; letter-spacing: 1px; line-height: 1.3; margin: 0; padding: 0; text-align: center\" align=\"center\">\r\n"
				+ "                                                                                                   Notification Service\r\n"
				+ "                                                                                                </p>\r\n"
				+ "                                                                                             </a>\r\n"
				+ "                                                                                          </td>\r\n"
				+ "                                                                                       </tr>\r\n"
				+ "                                                                                    </tbody>\r\n"
				+ "                                                                                 </table>\r\n"
				+ "                                                                              </td>\r\n"
				+ "                                                                           </tr>\r\n"
				+ "                                                                        </tbody>\r\n"
				+ "                                                                     </table>\r\n"
				+ "                                                                  </th>\r\n"
				+ "                                                                  <th class=\"expander\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; visibility: hidden; width: 0\" align=\"left\"></th>\r\n"
				+ "                                                               </tr>\r\n"
				+ "                                                            </tbody>\r\n"
				+ "                                                         </table>\r\n"
				+ "                                                      </th>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                             <table class=\" spacer \" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <td height=\"30px\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 30px; font-weight: normal; hyphens: auto; line-height: 30px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">&nbsp;</td>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                          </td>\r\n"
				+ "                                       </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                 </table>\r\n"
				+ "                                 <table class=\"have-questions-wrapper  container\" align=\"center\" style=\"background-color: #F5F5F5 !important; border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; text-align: inherit; vertical-align: top; width: 100% !important\" bgcolor=\"#F5F5F5\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                       <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                          <td style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">\r\n"
				+ "                                             <table class=\" spacer \" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <td height=\"24px\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 24px; font-weight: normal; hyphens: auto; line-height: 24px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">&nbsp;</td>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                             <table class=\"milkyway-content row\" style=\"border-collapse: collapse; border-spacing: 0; display: table; hyphens: none; margin: auto; max-width: 100%; padding: 0; position: relative; text-align: left; vertical-align: top; width: 280px !important\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <th class=\" small-12 large-12 columns first last\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0; text-align: left; width: 564px\" align=\"left\">\r\n"
				+ "                                                         <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                            <tbody>\r\n"
				+ "                                                               <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                                  <th style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left\" align=\"left\">\r\n"
				+ "                                                                     <img width=\"10\" src=\"https://i.ibb.co/XV8v0rj/Yanyana-Siyah-1-copy.png\" style=\"-ms-interpolation-mode: bicubic; clear: both; display: block; float: none; margin: 0 auto; max-width: 50%; outline: none; text-align: center; text-decoration: none; width: auto\">\r\n"
				+ "                                                                     <h3 style=\"color: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 20px; font-weight: 600; line-height: 26px; margin: 10 10 10px; padding: 0; text-align: center; word-wrap: normal\" align=\"left\">UNIT TESTING OR COMPONENT TESTING</h3>\r\n"
				+ "                                                                     <p class=\"help-center\" style=\"color: #6F7881; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 15px 0 10px; padding: 0; text-align: center\" align=\"left\">\r\n"
				+ "                                                                        Is a level of software testing where individual units / components of a software are tested. The purpose is to validate that each unit of the software performs as designed.\r\n"
				+ "                                                                     </p>\r\n"
				+ "                                                                  </th>\r\n"
				+ "                                                                  <th class=\"expander\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; visibility: hidden; width: 0\" align=\"left\"></th>\r\n"
				+ "                                                               </tr>\r\n"
				+ "                                                            </tbody>\r\n"
				+ "                                                         </table>\r\n"
				+ "                                                      </th>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                             <table class=\" spacer \" style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <td height=\"24px\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 24px; font-weight: normal; hyphens: auto; line-height: 24px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">&nbsp;</td>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                          </td>\r\n"
				+ "                                       </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                 </table>\r\n"
				+ "                              </td>\r\n"
				+ "                           </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                     </table>\r\n"
				+ "                     <table class=\" spacer  float-center\" align=\"center\" style=\"border-collapse: collapse; border-spacing: 0; float: none; margin: 0 auto; padding: 0; text-align: center; vertical-align: top; width: 100%\">\r\n"
				+ "                        <tbody>\r\n"
				+ "                           <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                              <td height=\"20px\" style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 20px; font-weight: normal; hyphens: auto; line-height: 20px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">&nbsp;</td>\r\n"
				+ "                           </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                     </table>\r\n"
				+ "                     <table class=\"emailer-footer container float-center\" align=\"center\" style=\"background-color: transparent !important; border-collapse: collapse; border-spacing: 0; float: none; margin: 0 auto; padding: 0; text-align: center; vertical-align: top; width: 580px\" bgcolor=\"transparent\">\r\n"
				+ "                        <tbody>\r\n"
				+ "                           <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                              <td style=\"-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 1.3; margin: 0; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word\" align=\"left\" valign=\"top\">\r\n"
				+ "                                 <table class=\" row\" style=\"border-collapse: collapse; border-spacing: 0; display: table; padding: 0; position: relative; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                       <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                          <th class=\" small-12 large-4 columns first\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0 8px 16px 16px; text-align: left; width: 177.3333333333px\" align=\"left\">\r\n"
				+ "                                             <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <th style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left\" align=\"left\"></th>\r\n"
				+ "                                                      <th class=\"emailer-border-bottom small-12 large-11 columns first\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0 0 16px; text-align: left; width: 91.666666%\" align=\"left\">\r\n"
				+ "                                                         <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                            <tbody>\r\n"
				+ "                                                               <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                                  <th style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left\" align=\"left\">\r\n"
				+ "                                                                  </th>\r\n"
				+ "                                                               </tr>\r\n"
				+ "                                                            </tbody>\r\n"
				+ "                                                         </table>\r\n"
				+ "                                                      </th>\r\n"
				+ "                                                      <th class=\"show-for-large small-12 large-1 columns last\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0 0 16px; text-align: left; width: 8.333333%\" align=\"left\">\r\n"
				+ "                                                         <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                            <tbody>\r\n"
				+ "                                                               </th></tr>\r\n"
				+ "                                                            </tbody>\r\n"
				+ "                                                         </table>\r\n"
				+ "                                                      </th>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                          </th>\r\n"
				+ "                                          <th class=\" small-12 large-4 columns\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0 8px 16px; text-align: left; width: 177.3333333333px\" align=\"left\">\r\n"
				+ "                                             <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                   <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                      <th style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left\" align=\"left\"></th>\r\n"
				+ "                                                      <th class=\"emailer-border-bottom small-12 large-11 columns first\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0 0 16px; text-align: left; width: 91.666666%\" align=\"left\">\r\n"
				+ "                                                         <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                            </p>\r\n"
				+ "                                                            </th></tr></tbody>\r\n"
				+ "                                                         </table>\r\n"
				+ "                                                      </th>\r\n"
				+ "                                                      <th class=\"show-for-large small-12 large-1 columns last\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0 auto; padding: 0 0 16px; text-align: left; width: 8.333333%\" align=\"left\">\r\n"
				+ "                                                         <table style=\"border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%\">\r\n"
				+ "                                                            <tbody>\r\n"
				+ "                                                               <tr style=\"padding: 0; text-align: left; vertical-align: top\" align=\"left\">\r\n"
				+ "                                                                  <th style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left\" align=\"left\">\r\n"
				+ "                                                                  </th>\r\n"
				+ "                                                               </tr>\r\n"
				+ "                                                            </tbody>\r\n"
				+ "                                                         </table>\r\n"
				+ "                                                      </th>\r\n"
				+ "                                                   </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                             </table>\r\n"
				+ "                                          </th>\r\n"
				+ "                                          <p class=\"text-center email-tag-line\" style=\"color: #6F7881; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.5; margin: 0; padding: 0; text-align: center\" align=\"center\">\r\n"
				+ "                                             Made with ❤️ in Warwickshire\r\n"
				+ "                                          </p>\r\n"
				+ "                                          <p class=\"universe-address\" style=\"color: #6F7881; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.5; margin: 0; padding: 0; text-align: center !important\" align=\"center\">\r\n"
				+ "                                             United Kingdom\r\n"
				+ "                                          </p>\r\n"
				+ "                                          <p class=\"help-email-address text-center\" style=\"color: #6F7881; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.5; margin: 0; padding: 0; text-align: center\" align=\"center\">\r\n"
				+ "                                             <span class=\"text-divider\" style=\"margin-left: 10px; margin-right: 10px\">\r\n"
				+ "                                             ©2020\r\n"
				+ "                                             <a href=\"https://e-bursum.com/\" style=\"color: #4E78F1; font-family: Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; text-decoration: none\" target=\"_blank\">\r\n"
				+ "                                             http://aerosimo.com\r\n"
				+ "                                          </p>\r\n"
				+ "                                          </th>\r\n"
				+ "                                          <th class=\"expander\" style=\"color: #1C232B; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; visibility: hidden; width: 0\" align=\"left\"></th>\r\n"
				+ "                                       </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                 </table>\r\n"
				+ "                                 </th>\r\n"
				+ "                           </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                     </table>\r\n"
				+ "               </td>\r\n"
				+ "            </tr>\r\n"
				+ "         </tbody>\r\n"
				+ "      </table>\r\n"
				+ "      </center>\r\n"
				+ "      </td>\r\n"
				+ "      </tr>\r\n"
				+ "      </tbody></table>\r\n"
				+ "   </body>\r\n"
				+ "</html>";	
		String actual;
		actual = mailer.SendEmail("support@aerosimo.com", "Test e-mail (junit)", emailMessage, "");	
		String expected;
		expected = "Successfully send email";
		// check for equality
		Assertions.assertEquals(expected, actual,"This should send a test email notification to support@aerosimo.com");
	}

}